spring.application.name=Rooms
server.port=8082
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

spring.datasource.url = jdbc:postgresql://localhost:5432/dp_rooms
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto = update #Hibernate ddl auto (create, create-drop, update, validate). #When serious use validate?
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#rsa.public-key=classpath:certifications/public.pem
#rsa.private-key=classpath:certifications/private.pem

#spring.servlet.multipart.max-file-size=50MB
#spring.servlet.multipart.max-request-size=50MB

logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}

logging.level.com.mm_mk.Rooms=ERROR
logging.level.org.springframework=ERROR
logging.level.org.springframework.security=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.apache.tomcat=ERROR
logging.level.org.apache.catalina=ERROR

#logging.level.org.springframework.security=TRACE
#logging.level.com.mm-mk.Rooms=DEBUG
#logging.level.org.springframework=DEBUG
#logging.level.org.apache.tomcat=DEBUG
#logging.level.org.apache.catalina=DEBUG
#logging.level.org.hibernate=INFO
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
#logging.level.org.hibernate.stat=DEBUG
#logging.level.org.hibernate.SQL_SLOW=INFO
#logging.level.org.hibernate.pretty=INFO
#logging.level.org.hibernate.cache=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.springframework.jdbc.core=TRACE

logging.path=/logs

spring.data.jdbc.repositories.enabled=false
spring.jpa.hibernate.ddl-auto=validate

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.exchange.rooms=rooms.exchange
rabbitmq.routingkey.room.created=room.created
rabbitmq.routingkey.user.joined=user.joined
rabbitmq.routingkey.room.deleted=room.deleted
rabbitmq.routingkey.user.left=user.left
rabbitmq.routingkey.user.kicked=user.kicked
rabbitmq.routingkey.user.muted=user.muted

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
